### ISSUE TITLE
Dependency on PyYAML 5.1

### ISSUE THREAD

**Issue by atondwal** [fakefred/memethesis-cli#4]
I'm not sure how pip encodes dependencies, but I ran into [this problem](https://stackoverflow.com/questions/55551191/module-yaml-has-no-attribute-fullloader) after installing with
```
python3 -m pip install memethesis --user
```
I get
```
[1] atondwal@anish-kudu> python3 -m memethesis                                                       ~
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/atondwal/.local/lib/python3.6/site-packages/memethesis/__main__.py", line 4, in <module>
    from .meme.vertical import make_vertical
  File "/home/atondwal/.local/lib/python3.6/site-packages/memethesis/meme/vertical.py", line 12, in <module>
    FORMATS = read_formats()
  File "/home/atondwal/.local/lib/python3.6/site-packages/memethesis/format_utils.py", line 11, in read_formats
    Loader=yaml.FullLoader)
AttributeError: module 'yaml' has no attribute 'FullLoader'
````
fixed by
```
python3 -m pip install -U PyYAML
```

Is there some way to include a version bound for the PyYAML dependency?

**Comment by fakefred** [comment]
Yes, there is, and it's fixed by now by a brain more sober than mine: #5
